<?php

namespace Wixair\ReparacionesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReparacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReparacionRepository extends EntityRepository
{
}
