<?php

namespace WhiteOctober\TCPDFBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class TCPDFController__JMSInjector
{
    public static function inject($container) {
        $instance = new \WhiteOctober\TCPDFBundle\Controller\TCPDFController();
        return $instance;
    }
}
