<?php

namespace Wixair\ReparacionesBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ReparacionController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Wixair\ReparacionesBundle\Controller\ReparacionController();
        return $instance;
    }
}
