<?php

namespace Proxies\__CG__\Wixair\ReparacionesBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Reparacion extends \Wixair\ReparacionesBundle\Entity\Reparacion implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setFechaEntrada($fechaEntrada)
    {
        $this->__load();
        return parent::setFechaEntrada($fechaEntrada);
    }

    public function getFechaEntrada()
    {
        $this->__load();
        return parent::getFechaEntrada();
    }

    public function setFechaSalida($fechaSalida)
    {
        $this->__load();
        return parent::setFechaSalida($fechaSalida);
    }

    public function getFechaSalida()
    {
        $this->__load();
        return parent::getFechaSalida();
    }

    public function setNombre($nombre)
    {
        $this->__load();
        return parent::setNombre($nombre);
    }

    public function getNombre()
    {
        $this->__load();
        return parent::getNombre();
    }

    public function setTlf($tlf)
    {
        $this->__load();
        return parent::setTlf($tlf);
    }

    public function getTlf()
    {
        $this->__load();
        return parent::getTlf();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setTipoEquipo($tipoEquipo)
    {
        $this->__load();
        return parent::setTipoEquipo($tipoEquipo);
    }

    public function getTipoEquipo()
    {
        $this->__load();
        return parent::getTipoEquipo();
    }

    public function setNumeroSerie($numeroSerie)
    {
        $this->__load();
        return parent::setNumeroSerie($numeroSerie);
    }

    public function getNumeroSerie()
    {
        $this->__load();
        return parent::getNumeroSerie();
    }

    public function setAccesorios($accesorios)
    {
        $this->__load();
        return parent::setAccesorios($accesorios);
    }

    public function getAccesorios()
    {
        $this->__load();
        return parent::getAccesorios();
    }

    public function setAveria($averia)
    {
        $this->__load();
        return parent::setAveria($averia);
    }

    public function getAveria()
    {
        $this->__load();
        return parent::getAveria();
    }

    public function setReparacion($reparacion)
    {
        $this->__load();
        return parent::setReparacion($reparacion);
    }

    public function getReparacion()
    {
        $this->__load();
        return parent::getReparacion();
    }

    public function setPrecio($precio)
    {
        $this->__load();
        return parent::setPrecio($precio);
    }

    public function getPrecio()
    {
        $this->__load();
        return parent::getPrecio();
    }

    public function setPresupuestoAceptado($presupuestoAceptado)
    {
        $this->__load();
        return parent::setPresupuestoAceptado($presupuestoAceptado);
    }

    public function getPresupuestoAceptado()
    {
        $this->__load();
        return parent::getPresupuestoAceptado();
    }

    public function setObservaciones($observaciones)
    {
        $this->__load();
        return parent::setObservaciones($observaciones);
    }

    public function getObservaciones()
    {
        $this->__load();
        return parent::getObservaciones();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'fecha_entrada', 'fecha_salida', 'nombre', 'tlf', 'email', 'tipo_equipo', 'numero_serie', 'accesorios', 'averia', 'reparacion', 'precio', 'presupuesto_aceptado', 'observaciones');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}